//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmAdo.EntityFramework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrmAdo.EntityFramework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ProviderManifest Namespace=&quot;CrmAdo&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2006/04/edm/providermanifest&quot;&gt;
        ///  &lt;Types&gt;
        ///
        ///    &lt;Type Name=&quot;uniqueidentifier&quot; PrimitiveTypeKind=&quot;Guid&quot;&gt;&lt;/Type&gt;  
        ///    &lt;Type Name=&quot;int&quot; PrimitiveTypeKind=&quot;Int32&quot;&gt;&lt;/Type&gt;
        ///    &lt;Type Name=&quot;bigint&quot; PrimitiveTypeKind=&quot;Int64&quot;&gt;&lt;/Type&gt;    
        ///    &lt;Type Name=&quot;float&quot; PrimitiveTypeKind=&quot;Double&quot;&gt;&lt;/Type&gt;
        ///    &lt;Type Name=&quot;real&quot; PrimitiveTypeKind=&quot;Single&quot;&gt;&lt;/Type&gt;    
        ///    &lt;Type Name=&quot;decimal&quot; PrimitiveTypeKind=&quot;Decimal&quot;&gt;
        ///      &lt;FacetDescriptions&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CrmEfProviderServices_ProviderManifest {
            get {
                return ResourceManager.GetString("CrmEfProviderServices_ProviderManifest", resourceCulture);
            }
        }
    }
}
